#!/bin/bash

## #ddev-generated
## Description: executes a script from tools/scripts/laravel
## Usage: dot
## Example: ddev dot
## ExecRaw: true

find tools/scripts/laravel -type f | fzf --preview="cat _" | xargs -I _ bash -c "_"
