#!/bin/bash

## #ddev-generated
## Description: Opens up a fish shell in the container or executs a command within a fish shell
## Usage: dot
## Example: ddev dot
## ExecRaw: true

find tools/scripts/laravel | fzf --preview="cat _" | xargs -I _ exec bash -c "$_"
