#ddev-generated
# Configuration for ddev-get-dot add-on

# Install fzf via package manager for better reliability
webimage_extra_packages:
  - fzf

# Environment variables for the dot command
web_environment:
  # default mountpoint inside the container
  DDEV_DOT_ROOT_PATH: /var/www/html
  # default location of your scripts relative to project root
  DDEV_DOT_SCRIPT_PATH: tools/scripts