#ddev-generated
# Simple template to demonstrate addon-template
services:
  addon-template:
    container_name: ddev-${DDEV_SITENAME}-addon-template
    image: busybox:stable
    command: tail -f /dev/null
    restart: "no"
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT

    volumes:
    - ".:/mnt/ddev_config"
    - "ddev-global-cache:/mnt/ddev-global-cache"



webimage_extra_packages:
  - fzf

web_environment:
  # default mountpoint inside the container
  DDEV_DOT_ROOT_PATH: /var/www/html
  # default location of your scripts relative to project root
  DDEV_DOT_SCRIPT_PATH: tools/scripts